### ISSUE TITLE
jumpToPage function (via pageController) does not update page view indicators

### ISSUE THREAD

**Issue by dcoleyoung** [figengungor/page_view_indicators#1]
When running the jumpToPage function, the indicators remain on the current page.  

By contrast, The animateToPage function updates the indicators correctly.

**Comment by figengungor** [comment]
Is this still an issue? If you can share a code snippet, It'll be helpful to investigate.

**Comment by dcoleyoung** [comment]
This looks fine now as testing this code: 

  _buildPageView() {
    return Column(children: [GestureDetector(
        onTap: () => _pageController.jumpToPage(3),
        child: Text('Jump')), Container(
      color: Colors.black87,
      height: _boxHeight,
      child: PageView.builder(
          itemCount: _items.length,
          controller: _pageController,
          itemBuilder: (BuildContext context, int index) {
            return Center(
              child: FlutterLogo(
                colors: _items[index],
                size: 50.0,
              ),
            );
          },
          onPageChanged: (int index) {
            _currentPageNotifier.value = index;
          }),
    )]);
  }
