### ISSUE TITLE
How to scroll infinitely?

### ISSUE THREAD

**Issue by SuYungCheng** [figengungor/page_view_indicators#5]
How can I scroll infinitely?
If I'm at the end page, and still scroll to right,
How can I go to the first page?
Thanks!

**Comment by figengungor** [comment]
Hi @SuYungCheng 

Here is a an example for you:

```
PageView.builder(
          controller: _pageController,
          itemBuilder: (BuildContext context, int index) {
            return Center(
              child: FlutterLogo(
                colors: _items[index % _items.length],
                size: 50.0,
              ),
            );
          },
          onPageChanged: (int index) {
            _currentPageNotifier.value = index % _items.length;
          }),
```

You don't set itemCount of PageView.builder and you take [index modulo item count] whenever you need to use index in your itemBuilder function.

Let's say you have 3 items. When you don't set itemCount of PageView.builder then it is incremented by one every time you scroll to right. 

1 2 3 4 5 6 list goes on
but taking these numbers modulo item count gives you
1 2 3 1 2 3
And you get what you want.

**Comment by SuYungCheng** [comment]
> Hi @SuYungCheng
> 
> Here is a an example for you:
> 
> ```
> PageView.builder(
>           controller: _pageController,
>           itemBuilder: (BuildContext context, int index) {
>             return Center(
>               child: FlutterLogo(
>                 colors: _items[index % _items.length],
>                 size: 50.0,
>               ),
>             );
>           },
>           onPageChanged: (int index) {
>             _currentPageNotifier.value = index % _items.length;
>           }),
> ```
> 
> You don't set itemCount of PageView.builder and you take [index modulo item count] whenever you need to use index in your itemBuilder function.
> 
> Let's say you have 3 items. When you don't set itemCount of PageView.builder then it is incremented by one every time you scroll to right.
> 
> 1 2 3 4 5 6 list goes on
> but taking these numbers modulo item count gives you
> 1 2 3 1 2 3
> And you get what you want.

thanks! This is very helpful!!

**Comment by figengungor** [comment]
I'm glad it's helpful.=)
